f = open("sample.txt",'r')
data = f.readline()
print(data)
print("now from here there is another lines printed")
data = f.readline()
print(data)
data = f.readline()
print(data)
data = f.readline()
print(data)
f.close()